services:
  # log:
  #   image: goharbor/harbor-log:v2.14.0
  #   container_name: harbor-log
  #   restart: always
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - CHOWN
  #     - DAC_OVERRIDE
  #     - SETGID
  #     - SETUID
  #   volumes:
  #     - ./log:/var/log/docker/:z
  #     - type: bind
  #       source: ./common/config/log/logrotate.conf
  #       target: /etc/logrotate.d/logrotate.conf
  #     - type: bind
  #       source: ./common/config/log/rsyslog_docker.conf
  #       target: /etc/rsyslog.d/rsyslog_docker.conf
  #   ports:
  #     - 127.0.0.1:1514:10514
  #   networks:
  #     - harbor

  redis:
    image: valkey/valkey:8.1.5-alpine3.23
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - harbor-redis-data:/data
    networks:
      harbor:
    # depends_on:
      # - log

  postgresql:
    image: postgres:18.1
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - ./storage/postgres:/var/lib/postgresql
      # - harbor-db-data:/var/lib/postgresql
    ports:
      - 127.0.0.1:5443:5432
    networks:
      harbor:
    env_file:
      - ./config/db/env
    # depends_on:
      # - log

  registry:
    image: goharbor/registry-photon:v2.14.0
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./storage/registry:/storage
      # - ./registry/:/etc/registry/:z
      - type: bind
        source: ./config/registry/registry-passwd
        target: /etc/registry/passwd
      - type: bind
        source: ./config/registry/registry-config.yml
        target: /etc/registry/config.yml
      - type: bind
        source: ./config/registry/root.crt
        target: /etc/registry/root.crt
      - type: bind
        source: ./config/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    # depends_on:
      # - log

  registryctl:
    image: goharbor/harbor-registryctl:v2.14.0
    container_name: registryctl
    env_file:
      - ./config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./storage/registry:/storage
      # - ./registry/:/etc/registry/:z
      - type: bind
        source: ./config/registry/registry-passwd
        target: /etc/registry/passwd
      - type: bind
        source: ./config/registry/registry-config.yml
        target: /etc/registry/config.yml
      - type: bind
        source: ./config/registry/root.crt
        target: /etc/registry/root.crt
      - type: bind
        source: ./config/trust-certificates
        target: /harbor_cust_cert
      - type: bind
        source: ./config/registryctl/registryctl-config.yml
        target: /etc/registryctl/config.yml
    networks:
      - harbor
    # depends_on:
    #   - log

  core:
    image: goharbor/harbor-core:v2.14.0
    container_name: harbor-core
    env_file:
      - ./config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - ./ca_download:/etc/core/ca/
      - ./storage/core:/data/
      - ./config/core/certificates/:/etc/core/certificates/
      - type: bind
        source: ./config/core/app.conf
        target: /etc/core/app.conf
      # only needed when you want https
      - type: bind
        source: ./config/secret/core/secret/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: ./config/secret/core/secret/secretkey
        target: /etc/core/key
      - type: bind
        source: ./config/trust-certificates
        target: /harbor_cust_cert
    networks:
      harbor:
    depends_on:
      # - log
      - registry
      - redis
      - postgresql

  jobservice:
    image: goharbor/harbor-jobservice:v2.14.0
    container_name: harbor-jobservice
    env_file:
      - ./config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ./storage/job_logs:/var/log/jobs
      - type: bind
        source: ./config/jobservice/config.yml
        target: /etc/jobservice/config.yml
      - type: bind
        source: ./config/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - core

  # portal:
  #   # image: goharbor/harbor-portal:v2.14.0
  #   image: 8gears.container-registry.com/8gcr-dev/harbor-portal:commercial-branding
  #   container_name: harbor-portal
  #   restart: always
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - CHOWN
  #     - SETGID
  #     - SETUID
  #     - NET_BIND_SERVICE
  #   volumes:
  #     - type: bind
  #       source: ./common/config/portal/nginx.conf
  #       target: /etc/nginx/nginx.conf
  #   networks:
  #     - harbor
  #   depends_on:
  #     # - log

  # proxy:
  #   image: goharbor/nginx-photon:v2.14.0
  #   container_name: nginx
  #   restart: always
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - CHOWN
  #     - SETGID
  #     - SETUID
  #     - NET_BIND_SERVICE
  #   volumes:
  #     - ./common/config/nginx:/etc/nginx:z
  #     - type: bind
  #       source: ./common/config/shared/trust-certificates
  #       target: /harbor_cust_cert
  #   networks:
  #     - harbor
  #   ports:
  #     - 8085:8080
  #   depends_on:
  #     - registry
  #     - core
  #     - portal
  #     # - log

  # trivy-adapter:
  #   container_name: trivy-adapter
  #   image: goharbor/trivy-adapter-photon:v2.14.0
  #   environment:
  #     - SCANNER_REDIS_URL=redis://redis:6379
  #   restart: always
  #   cap_drop:
  #     - ALL
  #   depends_on:
  #     # - log
  #     - redis
  #   networks:
  #     - harbor
  #   volumes:
  #     - type: bind
  #       source: ./opt/harbor-podman/trivy-adapter/trivy
  #       target: /home/scanner/.cache/trivy
  #     - type: bind
  #       source: ./opt/harbor-podman/trivy-adapter/reports
  #       target: /home/scanner/.cache/reports
  #     - type: bind
  #       source: ./common/config/shared/trust-certificates
  #       target: /harbor_cust_cert

volumes:
  harbor-db-data:
  harbor-redis-data:

networks:
  harbor:
